# Generated by Django 4.2.3 on 2023-07-24 09:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('note', ckeditor.fields.RichTextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('sem_one_reg_begins', models.DateField()),
                ('sem_one_reg_ends', models.DateField()),
                ('sem_one_cls_begins', models.DateField()),
                ('sem_one_cls_ends', models.DateField()),
                ('sem_one_brk_begins', models.DateField()),
                ('sem_one_brk_ends', models.DateField()),
                ('sem_two_reg_begins', models.DateField()),
                ('sem_two_reg_ends', models.DateField()),
                ('sem_two_cls_begins', models.DateField()),
                ('sem_two_cls_ends', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='Department of ', max_length=255, unique=True)),
                ('desc', ckeditor.fields.RichTextField(max_length=1500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('desc', ckeditor.fields.RichTextField(max_length=700)),
                ('hecas_resid', models.FloatField()),
                ('hecas_non_resid', models.FloatField()),
                ('ss_resid', models.FloatField()),
                ('ss_non_resid', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_name', models.CharField(max_length=255)),
                ('about', ckeditor.fields.RichTextField(max_length=700)),
                ('img', models.ImageField(default='default.png', upload_to='inst/')),
                ('vision', ckeditor.fields.RichTextField(max_length=350)),
                ('mission', ckeditor.fields.RichTextField(max_length=350)),
                ('is_active', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PngNqf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nqf_level', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'PNG NQF',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_name', models.CharField(default='National Certificate in ', max_length=255, unique=True)),
                ('prog_code', models.CharField(max_length=10, unique=True)),
                ('prog_duration', models.IntegerField()),
                ('prog_quota', models.IntegerField()),
                ('prog_description', ckeditor.fields.RichTextField(max_length=2500)),
                ('prog_requirement', ckeditor.fields.RichTextField(default='LL grade greate than B', max_length=1000)),
                ('is_active', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.institution')),
                ('nqf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pngnqf')),
            ],
            options={
                'ordering': ['-prog_name'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=700, unique=True)),
                ('intro', ckeditor.fields.RichTextField(max_length=700)),
                ('img', models.ImageField(blank=True, null=True, unique=True, upload_to='notices/')),
                ('main_body', ckeditor.fields.RichTextField(max_length=5000)),
                ('outro', ckeditor.fields.RichTextField(max_length=700)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.programme')),
            ],
        ),
        migrations.CreateModel(
            name='LatestUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=700, unique=True)),
                ('intro', ckeditor.fields.RichTextField(max_length=700)),
                ('img', models.ImageField(blank=True, default='default.png', null=True, unique=True, upload_to='updates/')),
                ('main_body', ckeditor.fields.RichTextField(max_length=5000)),
                ('outro', ckeditor.fields.RichTextField(max_length=700)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.institution')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ImageLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(default='default.png', unique=True, upload_to='img_lib/')),
                ('desc', models.CharField(max_length=400)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trade')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=255)),
                ('postal_address', models.CharField(max_length=255)),
                ('email', models.EmailField(default='youremail@example.com', max_length=255)),
                ('landline', models.IntegerField()),
                ('digicel', models.IntegerField()),
                ('telikom', models.IntegerField()),
                ('vodaphone', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.institution')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
