# Generated by Django 4.2.3 on 2023-08-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academiccalendar',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created']},
        ),
    ]
