# Generated by Django 4.2.3 on 2023-07-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_academiccalendar_is_active_feestructure_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept',
            field=models.CharField(default='Department of ', max_length=255),
        ),
        migrations.AlterField(
            model_name='programme',
            name='prog_name',
            field=models.CharField(default='National Certificate in ', max_length=255),
        ),
    ]
