# Generated by Django 4.2.3 on 2023-07-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_department_dept_alter_programme_prog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='desc',
            field=models.TextField(max_length=1500),
        ),
    ]
