# Generated by Django 4.2.3 on 2023-08-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='designation',
            field=models.CharField(default='Deputy Principal', max_length=255),
            preserve_default=False,
        ),
    ]
