# Generated by Django 4.2.3 on 2023-07-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_department_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='prog_requirement',
            field=models.TextField(default='LL grade greate than B', max_length=1000),
        ),
    ]
