# Generated by Django 4.2.3 on 2023-07-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_programme_prog_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestupdate',
            name='title',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=700),
        ),
    ]
