# Generated by Django 4.2.3 on 2023-07-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_latestupdate_title_alter_notice_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept',
            field=models.CharField(default='Department of ', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='year',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='imagelibrary',
            name='img',
            field=models.ImageField(default='default.png', unique=True, upload_to='img_lib/'),
        ),
        migrations.AlterField(
            model_name='latestupdate',
            name='img',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='updates/'),
        ),
        migrations.AlterField(
            model_name='latestupdate',
            name='title',
            field=models.CharField(max_length=700, unique=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='img',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='updates/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=700, unique=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='prog_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='prog_name',
            field=models.CharField(default='National Certificate in ', max_length=255, unique=True),
        ),
    ]
