# Generated by Django 4.2.3 on 2023-07-16 04:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_department_dept_alter_feestructure_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='desc',
            field=ckeditor.fields.RichTextField(max_length=1500),
        ),
    ]
