# Generated by Django 4.2.3 on 2023-07-16 04:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_department_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='desc',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='desc',
            field=ckeditor.fields.RichTextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='institution',
            name='about',
            field=ckeditor.fields.RichTextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='institution',
            name='mission',
            field=ckeditor.fields.RichTextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='institution',
            name='vision',
            field=ckeditor.fields.RichTextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='latestupdate',
            name='intro',
            field=ckeditor.fields.RichTextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='latestupdate',
            name='main_body',
            field=ckeditor.fields.RichTextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='latestupdate',
            name='outro',
            field=ckeditor.fields.RichTextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='notice',
            name='intro',
            field=ckeditor.fields.RichTextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='notice',
            name='main_body',
            field=ckeditor.fields.RichTextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='notice',
            name='outro',
            field=ckeditor.fields.RichTextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='programme',
            name='prog_description',
            field=ckeditor.fields.RichTextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='programme',
            name='prog_requirement',
            field=ckeditor.fields.RichTextField(default='LL grade greate than B', max_length=1000),
        ),
    ]
