# Generated by Django 4.2.3 on 2023-07-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_desc_academiccalendar_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='img',
            field=models.ImageField(default='default1.png', upload_to='img_lib/'),
        ),
    ]
