# Generated by Django 4.2.3 on 2023-07-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_institution_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='img',
            field=models.ImageField(default='img_lib/default1.png', upload_to='img_lib/'),
        ),
    ]
