# Generated by Django 4.2.3 on 2023-07-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_department_is_active_trade_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='img',
            field=models.ImageField(default='default.png', upload_to='img_lib/'),
        ),
    ]
