# Generated by Django 4.2.3 on 2023-07-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_institution_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='img',
            field=models.ImageField(default='default.png', upload_to='img_lib/'),
        ),
    ]
