# Generated by Django 4.2.3 on 2023-07-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_institution_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='img',
            field=models.ImageField(default='default.png', upload_to='inst/'),
        ),
        migrations.AlterField(
            model_name='latestupdate',
            name='img',
            field=models.ImageField(blank=True, default='default.png', null=True, unique=True, upload_to='updates/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='img',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='notices/'),
        ),
    ]
